version: '3.4'

services:
  app:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m flask run --no-debugger --host 0.0.0.0 --port 8080"]
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 5678:5678
    environment:
      - FLASK_ENV=development
      - FLASK_APP=scheduler
      - DATABASE_URL=postgresql://postgres:I5RfarAOpFbNCnTQITY7NiSfln6BVSBmm8C1KxPkvOB6yLs4xBy2AE9c9G1v5rs@postgres:5432/league_scheduler
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=I5RfarAOpFbNCnTQITY7NiSfln6BVSBmm8C1KxPkvOB6yLs4xBy2AE9c9G1v5rs
      - POSTGRES_DB=league_scheduler
    ports: 
      - 5432:5432
